#!/usr/bin/env bash

VERBOSE=false
FILE=$1

while getopts 'v' OPT; do
    case $OPT in
        v) 
            VERBOSE=true
            FILE=$2;;
    esac
done

function verbose_echo {
    if [ $VERBOSE = true ]; then
        echo $@
    fi
}

if [ -f $FILE ]; then
    verbose_echo "$FILE already exists or is not a valid file name"
    exit 0
fi
verbose_echo "Creating $FILE"
touch $FILE || exit 1
verbose_echo 'Adding shebang line'
echo '#!/usr/bin/env bash' > $FILE || exit 1
verbose_echo 'Making file executable'
chmod +x $FILE || exit 1

