#!/usr/bin/env bash

SILENT=false
FILE=$1

while getopts 's' OPT; do
    case $OPT in
        s) 
            SILENT=true
            FILE=$2;;
    esac
done

function silent_echo {
    if [ $SILENT = false ]; then
        echo $@
    fi
}

if [ -f $FILE ]; then
    echo "$FILE already exists or is not a valid file name"
    exit 0
fi
silent_echo "Creating $FILE"
touch $FILE || exit 1
silent_echo 'Adding shebang line'
echo '#!/usr/bin/env bash' > $FILE || exit 1
silent_echo 'Making file executable'
chmod +x $FILE || exit 1

